# Config file for automatic testing at travis-ci.org
dist: xenial   # required for Python >= 3.7
language: python
python:
  - 3.6
  - 3.5
  - 3.7

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
    - python setup.py install
    - hash -r

# command to run tests, e.g. python setup.py test
script:
    - pytest -v

